Vagrant.configure(2) do |config|
  config.vm.hostname = "pinhole-deploy"
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "1024",
      "--paravirtprovider", "kvm", # for linux guest
      "--cpus", "2",
      "--ioapic", "on",
    ]
  end
  config.vm.network "forwarded_port", guest: 23464, host: 23464
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
  SHELL
end
