Vagrant.configure(2) do |config|
  config.vm.hostname = "bowtickets-deploy"
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "1024",
      "--paravirtprovider", "kvm", # for linux guest
      "--cpus", "2",
      "--ioapic", "on",
    ]
  end
  config.vm.network "forwarded_port", guest: 41534, host: 41534
  config.vm.network "forwarded_port", guest: 41535, host: 41535
  config.vm.network "forwarded_port", guest: 41536, host: 41536
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
  SHELL
end
